---
- name: 2day quiz
  hosts: serverc.test.com
  tasks:
    - name: packages install
      dnf:
        name:
          - httpd
          - php
          - php-mysqlnd
          - mariadb-server
          - vsftpd
        state: latest
   
    - name: start web service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes


    - name: start db service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
   
    - name: start ftp service
      ansible.builtin.service:
        name: vsftpd
        state: started
        enabled: yes


    - name: add firewall rule
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
       
    - name: copy index.php
      ansible.builtin.copy:
        src: ./index.php
        dest: /var/www/html/index.php
        mode: '0644'